# Generated by Django 4.2.5 on 2023-12-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("philanthrobid_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidder",
            name="name",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="name",
        ),
        migrations.AddField(
            model_name="bidder",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="philanthrobid_app.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="bid",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bidder",
            name="money_spent",
            field=models.IntegerField(),
        ),
    ]
