# Generated by Django 5.0 on 2023-12-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0002_remove_bidder_name_remove_listing_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
