# Generated by Django 5.0 on 2023-12-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='mininc',
            field=models.IntegerField(default=0),
        ),
    ]
