# Generated by Django 5.0 on 2023-12-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0005_listing_strtbid_alter_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidding_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_who_bid', to='philanthrobid_app.user'),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
