# Generated by Django 5.0 on 2023-12-31 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bidding_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_who_bid', to='philanthrobid_app.user', to_field='username'),
        ),
    ]
