# Generated by Django 5.0 on 2024-01-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0013_alter_listing_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='unpaidWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
