# Generated by Django 5.0 on 2024-01-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0017_unpaidwinner_id_of_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaidwinner',
            name='title',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unpaidwinner',
            name='unpaidName',
            field=models.ForeignKey(default='try', on_delete=django.db.models.deletion.CASCADE, related_name='userWhoHasntPaid', to='philanthrobid_app.user', to_field='username'),
            preserve_default=False,
        ),
    ]
