# Generated by Django 5.0 on 2024-01-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0018_unpaidwinner_title_unpaidwinner_unpaidname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unpaidwinner',
            name='id',
        ),
        migrations.AlterField(
            model_name='unpaidwinner',
            name='id_of_listing',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
