# Generated by Django 5.0 on 2024-01-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0019_remove_unpaidwinner_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unpaidWinner',
        ),
    ]
