# Generated by Django 5.0 on 2024-01-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0020_delete_unpaidwinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charities',
            fields=[
                ('customer_ID', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
