# Generated by Django 5.0 on 2024-01-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0021_charities'),
    ]

    operations = [
        migrations.AddField(
            model_name='charities',
            name='charId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charities',
            name='customer_ID',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
