# Generated by Django 5.0 on 2024-01-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0023_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
