# Generated by Django 5.0 on 2024-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0027_remove_listing_tags_remove_tag_id_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(blank=True, to='philanthrobid_app.tag'),
        ),
    ]
