# Generated by Django 5.0 on 2024-01-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0028_listing_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='tags',
        ),
    ]
