# Generated by Django 5.0 on 2024-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0029_remove_listing_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Dance',
            field=models.IntegerField(default=0.5),
        ),
        migrations.AddField(
            model_name='listing',
            name='E_Sports',
            field=models.IntegerField(default=0.5),
        ),
        migrations.AddField(
            model_name='listing',
            name='Education',
            field=models.IntegerField(default=0.5),
        ),
        migrations.AddField(
            model_name='listing',
            name='Music',
            field=models.IntegerField(default=0.5),
        ),
        migrations.AddField(
            model_name='listing',
            name='Spiritual',
            field=models.IntegerField(default=0.5),
        ),
        migrations.AddField(
            model_name='listing',
            name='Sports',
            field=models.IntegerField(default=0.5),
        ),
    ]
