# Generated by Django 5.0 on 2024-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0030_listing_dance_listing_e_sports_listing_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Dance',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='listing',
            name='E_Sports',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Education',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Music',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Spiritual',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Sports',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
    ]
