# Generated by Django 5.0 on 2024-01-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0031_alter_listing_dance_alter_listing_e_sports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='E_Sports',
            field=models.IntegerField(default=0),
        ),
    ]
