# Generated by Django 5.0 on 2024-01-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0032_alter_listing_e_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Dance',
            field=models.IntegerField(default=0),
        ),
    ]
