# Generated by Django 5.0 on 2024-01-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0033_alter_listing_dance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Dance',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='E_Sports',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='Education',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='Music',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='Spiritual',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='Sports',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='interactionCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Education',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Music',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Spiritual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Sports',
            field=models.IntegerField(default=0),
        ),
    ]
