# Generated by Django 5.0 on 2024-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0034_user_dance_user_e_sports_user_education_user_music_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Dance',
            field=models.DecimalField(decimal_places=5, default=0.25, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='E_Sports',
            field=models.DecimalField(decimal_places=5, default=0.25, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='Education',
            field=models.DecimalField(decimal_places=5, default=0.25, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='Music',
            field=models.DecimalField(decimal_places=5, default=0.25, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='Spiritual',
            field=models.DecimalField(decimal_places=5, default=0.25, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sports',
            field=models.DecimalField(decimal_places=5, default=0.25, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='interactionCount',
            field=models.IntegerField(default=1),
        ),
    ]
