# Generated by Django 5.0 on 2024-01-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0036_messagegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageGroup',
        ),
    ]
