# Generated by Django 5.0 on 2024-01-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0039_messages_message_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_data',
            field=models.TextField(),
        ),
    ]
