# Generated by Django 5.0 on 2024-01-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0040_alter_messages_message_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(default='ig', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='philanthrobid_app.user', to_field='username'),
            preserve_default=False,
        ),
    ]
