# Generated by Django 5.0 on 2024-01-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0041_messages_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
    ]
