# Generated by Django 5.0 on 2024-01-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0042_remove_messages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='days_to_end',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
