# Generated by Django 5.0 on 2024-01-30 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philanthrobid_app', '0043_listing_days_to_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 11, 53, 3, 589326, tzinfo=datetime.timezone.utc)),
        ),
    ]
