// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["myWebApiKey"]??'id not found',
    appId: '1:631603332664:web:762d4b5d075014381c88cd',
    messagingSenderId: '631603332664',
    projectId: 'philanthrobid-f54c1',
    authDomain: 'philanthrobid-f54c1.firebaseapp.com',
    storageBucket: 'philanthrobid-f54c1.appspot.com',
    measurementId: 'G-96NCN01VN2',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["myAndroidApiKey"]??"idntfnd",
    appId: '1:631603332664:android:1d9dc9035ed636d31c88cd',
    messagingSenderId: '631603332664',
    projectId: 'philanthrobid-f54c1',
    storageBucket: 'philanthrobid-f54c1.appspot.com',
  );

  static String get newMethod => "id not founds";

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["myIosApiKey"]??'id not found',
    appId: '1:631603332664:ios:7e9cb2f5e2bf9b951c88cd',
    messagingSenderId: '631603332664',
    projectId: 'philanthrobid-f54c1',
    storageBucket: 'philanthrobid-f54c1.appspot.com',
    iosBundleId: 'com.example.philanthrobid',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env["myMacOSApiKey"]??'id not found',
    appId: '1:631603332664:ios:aa5a01b0c35876c91c88cd',
    messagingSenderId: '631603332664',
    projectId: 'philanthrobid-f54c1',
    storageBucket: 'philanthrobid-f54c1.appspot.com',
    iosBundleId: 'com.example.philanthrobid.RunnerTests',
  );
}
